[package]
name = "rayon-ping-pong"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon="1.7"
tokio = {version="1.32", features=["sync"]}
